---
title: "Meta-analysis in Plant Pathology"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(gsheet)
library(janitor)
library(ggthemes)
library(cowplot)
library(colorspace)
library(patchwork)
library(wordcloud)
```

```{r}
dat <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1vYXB1Ag-ouLgo9nLIelP1V0hz-ki0f7p-aOCAkmuxKI/edit#gid=1058316481")
theme_set(theme_minimal_grid())
```

## Journals

```{r}
tab2 <- dat %>% 
  dplyr::select(journal) %>% 
   tabyl(journal) %>% 
  select(-percent)

wordcloud(words = tab2$journal, freq = tab2$n,  min.freq = 1, max.words=200, random.order=FALSE, rot.per=0.25, colors=brewer.pal(8, "Dark2"))



```

## Pubs by year and type

```{r}
p1 <- dat %>% 
  tabyl(pub_year, article_type) %>% 
  pivot_longer(names_to = "Type", 
               values_to = "n", 2:3) %>% 
  ggplot(aes(pub_year, n, fill = Type))+
 geom_col()+
  theme(legend.position = "bottom",
          panel.grid.major=element_line(colour="grey94"))+
 scale_fill_discrete_qualitative(palette = "cold")+
  scale_y_continuous(n.breaks = 10)+
  labs( x = "Publication year", y = "Number of publications")

```

## By Source type

```{r}
p2 <- dat %>% 
  filter(article_type == "Original Article") %>% 
  tabyl(data_source) %>% 
  ggplot(aes(reorder(data_source, -n), n, fill = n))+
  geom_col(fill = "#ACA4E2", width = 0.56)+
  geom_text(
    aes(x = data_source, y = n, label = n),
    position = position_dodge(width = 1),
    vjust = -0.5, size = 4) + 
  theme(legend.position = "bottom",
          panel.grid.major=element_line(colour="grey94"))+
scale_y_continuous(breaks = c(0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30))+
  labs(x = "", y = "Number of original articles")


```

# Figure 1: year and source

```{r}
#| fig-width: 7
#| fig-height: 10
(p1 / p2) +
  plot_annotation(tag_levels = "A")
ggsave("figs/figure11.png", width = 7, height =10, bg = "white")
```

## By objective and product type

```{r}
objective <- dat %>% 
  filter(article_type == "Original Article") %>% 
  tabyl(objective) |> 
  select(-percent)

type <- dat %>% 
  filter(article_type == "Original Article") %>% 
  filter(objective == "Product effects") %>% 
  tabyl(product_type) |> 
  select(-percent)
cbind(objective, type)

```

## Number of trials/studey per article

```{r}

summary(dat$n_trials_total)
```

## Effect sizes

```{r}
dat %>% 
  dplyr::select(effect_size_1, effect_size_2, effect_size_3) %>% 
  pivot_longer(names_to = "type", values_to = "value", 1:3) %>% 
  select(value) %>%
    filter(value != "NA") %>% 
  tabyl(value) |> 
  adorn_totals()
```

## Response variables

```{r}
tab <- dat %>% 
  dplyr::select(response1 , response2, response3, response4) %>% 
  pivot_longer(names_to = "type", values_to = "Variable", 1:4) %>% 
  select(Variable) %>%
    filter(Variable != "NA") %>% 
  tabyl(Variable) %>% 
  select(-percent)
tab

library(wordcloud)
wordcloud(words = tab$Variable, freq = tab$n,  min.freq = 1,           max.words=200, random.order=FALSE, rot.per=0.25,            colors=brewer.pal(5, "Dark2"))


```
